# Generated by Django 6.0 on 2025-12-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('digital_wallet', 'Digital Wallet'), ('card', 'Card Payment')], max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qrcodes/')),
                ('instructions', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('processing_time', models.CharField(default='5-15 minutes', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.CreateModel(
            name='RechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='User-provided transaction reference', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Amount + Fee', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('verified', 'Payment Verified')], default='unpaid', max_length=20)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('payment_details', models.TextField(blank=True, help_text='Additional payment information')),
                ('sender_account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sender_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('payment_made_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_recharges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RechargeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('payment_required', 'Payment Required'), ('payment_received', 'Payment Received'), ('approved', 'Recharge Approved'), ('rejected', 'Recharge Rejected'), ('processing', 'Processing')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cat.rechargerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rechargerequest',
            index=models.Index(fields=['transaction_id'], name='cat_recharg_transac_673b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargerequest',
            index=models.Index(fields=['status', 'payment_status'], name='cat_recharg_status_40490c_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargerequest',
            index=models.Index(fields=['user', 'requested_at'], name='cat_recharg_user_id_93e611_idx'),
        ),
    ]
