# Generated by Django 6.0 on 2025-12-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
