# Generated by Django 5.2.4 on 2025-11-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_alter_invitereward_profile_alter_profile_invite_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteLog',
        ),
    ]
