# Generated by Django 6.0 on 2025-12-22 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMainProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('last_claim_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('main_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.mainproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
                'unique_together': {('user', 'main_project')},
            },
        ),
    ]
