# Generated by Django 6.0 on 2025-12-22 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_usermainproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservip',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
