# Generated by Django 6.0 on 2025-12-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_uservip_purchase_date_delete_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='merchant_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
