# Generated by Django 6.0 on 2025-12-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_profile_bank_type_profile_merchant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
