# Generated by Django 6.0 on 2025-12-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0009_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
