# Generated by Django 6.0 on 2025-12-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0010_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
