# Generated by Django 6.0 on 2025-12-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0011_uservip_is_active_vip_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
